import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Image from "next/image";
const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakartaSans.variable} antialiased bg-zinc-100 font-sans`}
      >
        <Navbar />
        <main className="min-h-screen scroll-smooth pt-20 md:pt-26 lg:pt-28 px-4 md:px-22 lg:px-38">
          {children}
        </main>
        <div className="relative">
          <div className="absolute h-screen bg-linear-to-t from-primary/20 to-primary/10 w-full blur-2xl -top-[500px] -z-40"></div>
          <Image
            src={"/Vector.svg"}
            alt="Vector"
            className="w-full"
            width={0}
            height={0}
          />
        </div>
        <Footer />
      </body>
    </html>
  );
}
